spring:
  ai:
    dashscope:
      api-key: sk-2af15d17c512417bb55cc0ff26b52102
      chat:
        options:
          model: qwen-flash
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
        enabled: false
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
  datasource:
    url: jdbc:postgresql://改为你的公网地址/yu_ai_agent
    username: 改为你的用户名
    password: 改为你的密码
    ai:
      vectorstore:
        pgvector:
          index-type: HNSW
          dimensions: 1536
          distance-type: COSINE_DISTANCE
          max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yume.yumeaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: qMDnkH2B1141PyKhsVYwsLZ6
logging:
  level:
    org.springframework.ai: DEBUG