spring:
  application:
    name: yume-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-flash
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: gemma3:1b
        enabled: false
    mcp:
      client:
        sse:
          connections:
            server1:
              url: ${MCP_SERVER_URL:http://localhost:8127}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/yu_ai_agent}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    ai:
      vectorstore:
        pgvector:
          index-type: HNSW
          dimensions: 1536
          distance-type: COSINE_DISTANCE
          max-document-batch-size: 10000

server:
  port: 8124
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yume.yumeaiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

search-api:
  api-key: ${SEARCH_API_KEY}

logging:
  level:
    org.springframework.ai: DEBUG